---
title: "NAME AND LAST NAME HERE"
output: 
  html_document: 
    keep_md: yes
---





# Exercise # 1 - Frogs and human disturbance study
A researcher was keen to understand the effect of human disturbance on the abundance of 1 frog species in Spain (Iberian frogs Rana iberica).
The researcher collected data walking along 20 randomly selected transects along streams and ponds (length = 50m) and collected the following information:

frogs = number of frogs 
dist.recr = distance from the center of the transect to the closest recreational area, in meters (that is a proxy for human disturbance)
Here are the data resumed in 2 vectors:
```{r}
frogs = c(2,5,6,3,10,17,7,7,14,14,23,25,34,22,35,32,34,32,76,64)
dist.recr = c(25.214,74.179,124.080,173.885,223.130,272.089,321.511,370.401,420.477,470.176,520.328,570.669,619.342,669.151,718.762,766.833,815.155,863.224,910.411,957.578)

```
The researcher is aware that he has to collect confounding factors and likely information about water quality, but, prior to plan a massive data collection, he wants to understand preliminary if there is a pattern in the number of frogs depending on the distance to the closest recreational area. 
(i) Help the researcher running the analyses for him and fit the proper model to understand the effect of human disturbance on frog abundance. 
(ii) Plot predicted values with 95% Confidence intervals.
Make sure the researcher is able to understand your analyses and your preliminar results - provide short comments step by step so to justify your analyses and explain your final results. 


